# Generated by Django 3.1.1 on 2020-09-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('pk_product', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('product_description', models.TextField(verbose_name='Descrição do Produto')),
                ('product_stock', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produtos',
                'db_table': 'market_product',
            },
        ),
    ]
